# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellogophercamptest2 < Formula
  desc "hellogophercamptest2"
  homepage "https://github.com/ondrejsika/hellogophercamptest2"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hellogophercamptest2/releases/download/v0.1.0/hellogophercamptest2_v0.1.0_darwin_amd64.tar.gz"
      sha256 "99eaa8862ea6791daadbc6edf625cda2436d06e08712e71ff127f119abbe5f3f"

      def install
        bin.install "hellogophercamptest2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hellogophercamptest2/releases/download/v0.1.0/hellogophercamptest2_v0.1.0_darwin_arm64.tar.gz"
      sha256 "ad50e5f98d7353efb8c8db3becb6d975c0f7b88803196a179708cf9503253291"

      def install
        bin.install "hellogophercamptest2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest2/releases/download/v0.1.0/hellogophercamptest2_v0.1.0_linux_amd64.tar.gz"
        sha256 "af7bc7b93d9ece54e21a2fc6847dacfd399c5b3155ded61982472bbd37669b0d"

        def install
          bin.install "hellogophercamptest2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest2/releases/download/v0.1.0/hellogophercamptest2_v0.1.0_linux_arm64.tar.gz"
        sha256 "97018f6f392373c7c504f078c3e82209e0b3e8309440f487157e11acb4ae3c2a"

        def install
          bin.install "hellogophercamptest2"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/hellogophercamptest2
    EOS
  end

  test do
    system "#{bin}/hellogophercamptest2 version"
  end
end
