# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellogophercamptest < Formula
  desc "hellogophercamptest"
  homepage "https://github.com/ondrejsika/hellogophercamptest"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.3.0/hellogophercamptest_v0.3.0_darwin_amd64.tar.gz"
      sha256 "591938f61695d526728d46c77f38612c614c3c8f88643fc237558f0ede2b458c"

      def install
        bin.install "hellogophercamptest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.3.0/hellogophercamptest_v0.3.0_darwin_arm64.tar.gz"
      sha256 "237c68c079cf514042fe8aa830de65c5b1de02c0b05891c3d01bd4c7ea5ffaef"

      def install
        bin.install "hellogophercamptest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.3.0/hellogophercamptest_v0.3.0_linux_amd64.tar.gz"
        sha256 "0e81c9164201fa31ad72c32b3d9d315872acf62ef9e92c399a51d86cfd5c3113"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.3.0/hellogophercamptest_v0.3.0_linux_arm64.tar.gz"
        sha256 "934376e46d49bbf36dd0d89e60bb48ed15cf5a87e74a816a05beedbd29161d74"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/hellogophercamptest
    EOS
  end

  test do
    system "#{bin}/hellogophercamptest version"
  end
end
