# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellogophercamp < Formula
  desc "hellogophercamp"
  homepage "https://github.com/ondrejsika/hellogophercamp"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hellogophercamp/releases/download/v0.1.0/hellogophercamp_v0.1.0_darwin_amd64.tar.gz"
      sha256 "b130cb1fc6e8a491773978c12d53a6429e9dc2cef0a73e2af9999e116a5856ee"

      def install
        bin.install "hellogophercamp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hellogophercamp/releases/download/v0.1.0/hellogophercamp_v0.1.0_darwin_arm64.tar.gz"
      sha256 "e9bb6d8528e547ab8a082c044da1acd50e98051841d9426edc21ab1cc7eeca87"

      def install
        bin.install "hellogophercamp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamp/releases/download/v0.1.0/hellogophercamp_v0.1.0_linux_amd64.tar.gz"
        sha256 "25e31a0fec5f40232dc6758b8d7b78f3d5188720962562edf45f6558582af45c"

        def install
          bin.install "hellogophercamp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamp/releases/download/v0.1.0/hellogophercamp_v0.1.0_linux_arm64.tar.gz"
        sha256 "8e809e3bd2874dc7b4e963ebe0e246bd18725f83bbf1ecff823ad0b20a0924f1"

        def install
          bin.install "hellogophercamp"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/hellogophercamp
    EOS
  end

  test do
    system "#{bin}/hellogophercamp version"
  end
end
