# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellogophercamptest < Formula
  desc "hellogophercamptest"
  homepage "https://github.com/ondrejsika/hellogophercamptest"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.1.0/hellogophercamptest_v0.1.0_darwin_amd64.tar.gz"
      sha256 "ae119d73cc2a13e597481b1ffb152ced2e3b598719f8e0b58d242718562f2406"

      def install
        bin.install "hellogophercamptest"
      end
    end
    on_arm do
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.1.0/hellogophercamptest_v0.1.0_darwin_arm64.tar.gz"
      sha256 "0791081bf610d172c0687d6797711f001514f47a075f332ba76f1e2643f518ab"

      def install
        bin.install "hellogophercamptest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.1.0/hellogophercamptest_v0.1.0_linux_amd64.tar.gz"
        sha256 "d7aae894361221ec14808b6dfeb33d9f4fc009201d35a4f6e74198b93f223571"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.1.0/hellogophercamptest_v0.1.0_linux_arm64.tar.gz"
        sha256 "f58b819bb148ec7b1bfb163e061391f9cab4bb843c93b85cc4e15594d85787bb"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/hellogophercamptest
    EOS
  end

  test do
    system "#{bin}/hellogophercamptest version"
  end
end
