# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellogophercamptest < Formula
  desc "hellogophercamptest"
  homepage "https://github.com/ondrejsika/hellogophercamptest"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.2.0/hellogophercamptest_v0.2.0_darwin_amd64.tar.gz"
      sha256 "d9c9e518c241a419b6c518bacf938e0710caa54b8a7afe1614224deac6917397"

      def install
        bin.install "hellogophercamptest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.2.0/hellogophercamptest_v0.2.0_darwin_arm64.tar.gz"
      sha256 "d97ba0c0c77b92fcdf49240027ace7ab19ebdb83dd047a0cda2b44978be1e51d"

      def install
        bin.install "hellogophercamptest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.2.0/hellogophercamptest_v0.2.0_linux_amd64.tar.gz"
        sha256 "4c4bc1376fa31c5268fe51442de2b94db2deef266800def4d9931f5e0aa70ea2"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika/hellogophercamptest/releases/download/v0.2.0/hellogophercamptest_v0.2.0_linux_arm64.tar.gz"
        sha256 "d39b12b74296cdc4a686d2499a4bf023aafe6ed94202047868ff0ae67ed78505"

        def install
          bin.install "hellogophercamptest"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/hellogophercamptest
    EOS
  end

  test do
    system "#{bin}/hellogophercamptest version"
  end
end
