# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/ondrejsika/master"
  version "2025.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.4/master_v2025.5.4_darwin_amd64.tar.gz"
      sha256 "0adafaaa29c8ccf07167979aa246d9aa077de9128ffbde9fd41326fd239c5788"

      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.4/master_v2025.5.4_darwin_arm64.tar.gz"
      sha256 "4d5077fba23a5b48092b3e0952819c73923bab2bc8c7efe6d4a9ada41f38bb50"

      def install
        bin.install "master"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.4/master_v2025.5.4_linux_amd64.tar.gz"
      sha256 "60ef85ac1ae361746d7629d64d5194f579ea12ebcc5b633503ba9513baf12975"
      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.4/master_v2025.5.4_linux_arm64.tar.gz"
      sha256 "19e52da917c65ac825b574cddee67ea6ee33caa26191a1356f1ce7f675e9e936"
      def install
        bin.install "master"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
