# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/ondrejsika/master"
  version "2025.5.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.6/master_v2025.5.6_darwin_amd64.tar.gz"
      sha256 "f90b8f345babb8cf4e3f4490fa159e273fcf6996b9db43ed0a059d46816117db"

      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.6/master_v2025.5.6_darwin_arm64.tar.gz"
      sha256 "c52ce59de077deb2b43a8b8ed676465cace87afd52ca5e52ea7fd470af00b0e5"

      def install
        bin.install "master"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.6/master_v2025.5.6_linux_amd64.tar.gz"
      sha256 "2d9fb25c079ad77941f43c94e2712d1ecf48e2e5eb368e4d2b8c0b3359ffce1d"
      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.6/master_v2025.5.6_linux_arm64.tar.gz"
      sha256 "cc18e7380a071747480db8c6597507ca0f70ba1705967af0437f3ee74ac22842"
      def install
        bin.install "master"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
