# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/ondrejsika/master"
  version "2025.5.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.10/master_v2025.5.10_darwin_amd64.tar.gz"
      sha256 "11b38cbae083483318d1536638ad16192bdf0d217c23b4d5cc97eca66c7201bd"

      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.10/master_v2025.5.10_darwin_arm64.tar.gz"
      sha256 "6e97871c9d741811afc66ef3869b2eda23557e26c14dc5a578048765777a3b47"

      def install
        bin.install "master"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.10/master_v2025.5.10_linux_amd64.tar.gz"
      sha256 "0f8f71e5251343a094d44bba6b38ef7873d9650e2e9f63280491db0c6d7e875f"
      def install
        bin.install "master"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/master/releases/download/v2025.5.10/master_v2025.5.10_linux_arm64.tar.gz"
      sha256 "3797cb02bb8d87a26d24441ae49573b41ac7983eab93e261afc0f8a58069deb1"
      def install
        bin.install "master"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
