# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionBackupEdge < Formula
  desc "notion-backup"
  homepage "https://github.com/ondrejsika/notion-backup"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/notion-backup/releases/download/v0.1.0/notion-backup_v0.1.0_darwin_arm64.tar.gz"
      sha256 "c6d99d33c9d3d3c8bc6e90e623f41268ce91f140c29f153c1f4c1c00106ce261"

      def install
        bin.install "notion-backup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/notion-backup/releases/download/v0.1.0/notion-backup_v0.1.0_darwin_amd64.tar.gz"
      sha256 "e826ef3aa5bff122bc408278cd870d33c86689e97b330435115013a07702bfe4"

      def install
        bin.install "notion-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/notion-backup/releases/download/v0.1.0/notion-backup_v0.1.0_linux_arm64.tar.gz"
      sha256 "c7955ab53ab4959689b71ce00fbe8c58b077f7544941141d3624b7fcbfbbdba6"

      def install
        bin.install "notion-backup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/notion-backup/releases/download/v0.1.0/notion-backup_v0.1.0_linux_amd64.tar.gz"
      sha256 "6c733ee22ddcd7c98879532cf44c25d353e92140d5936d781d67f7f60b38acab"

      def install
        bin.install "notion-backup"
      end
    end
  end

  conflicts_with "notion-backup"

  def caveats; <<~EOS
    How to use this binary: https://github.com/ondrejsika/notion-backup
  EOS
  end

  test do
    system "#{bin}/notion-backup version"
  end
end
