# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osu < Formula
  desc "osu"
  homepage "https://github.com/ondrejsika/osu"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/osu/releases/download/v0.1.0/osu_v0.1.0_darwin_amd64.tar.gz"
      sha256 "a144bbf595dd9fc6ee0b4b6b844c214fe1f2e4453a990bcc15e3e7caf6daa1ad"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/osu/releases/download/v0.1.0/osu_v0.1.0_darwin_arm64.tar.gz"
      sha256 "9afe93e9c48c7da0d67ca8cbab1ba6e35c615d03b13427616923e8818feff205"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/osu/releases/download/v0.1.0/osu_v0.1.0_linux_amd64.tar.gz"
      sha256 "48cca5ac8356b41c4414023144d76a7e335f05a581bf06b0e276d271b3a7b5f2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/osu/releases/download/v0.1.0/osu_v0.1.0_linux_arm64.tar.gz"
      sha256 "ec2b304be352a7520f84f56b92aa80fd932f82ef668ae3500504e952b3bfa452"
    end
  end

  conflicts_with "osu-edge"

  def install
    bin.install "osu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/ondrejsika/osu
  EOS
  end

  test do
    system "#{bin}/osu version"
  end
end
