# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrainingCli < Formula
  desc "training-cli"
  homepage "https://github.com/ondrejsika/training-cli"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.6.0/training-cli_v0.6.0_darwin_amd64.tar.gz"
      sha256 "cd1b3b60e38be16c32a2dd591506294039e2989ec6d9e7a93f73a5660d5635f5"

      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.6.0/training-cli_v0.6.0_darwin_arm64.tar.gz"
      sha256 "72396a2e71ed9e5050736cc542858cf684fb5f4e29546be1addce18bcc644381"

      def install
        bin.install "training-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.6.0/training-cli_v0.6.0_linux_amd64.tar.gz"
      sha256 "414803eb5e1663bd639efca8e2ef56682ac87198df2a14cb29c643e4fff91ecc"
      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.6.0/training-cli_v0.6.0_linux_arm64.tar.gz"
      sha256 "a97816b353f88442fbfc6525453088ec9a35f50639e2c7d4716eedfbf84be20f"
      def install
        bin.install "training-cli"
      end
    end
  end

  conflicts_with "training-cli-edge"

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/training-cli
    EOS
  end

  test do
    system "#{bin}/training-cli version"
  end
end
