# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrainingCliEdge < Formula
  desc "training-cli"
  homepage "https://github.com/ondrejsika/training-cli"
  version "0.3.0-dev-1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.3.0-dev-1/training-cli_v0.3.0-dev-1_darwin_arm64.tar.gz"
      sha256 "52f386981b3d78a2866291c3fe328c0dab2575da1e3a74ce7ede129392586c76"

      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.3.0-dev-1/training-cli_v0.3.0-dev-1_darwin_amd64.tar.gz"
      sha256 "0bcb3d3b659b1e0c90d339dd9c14b09668af564b1d08a8a1d8d35eb1df0e8392"

      def install
        bin.install "training-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.3.0-dev-1/training-cli_v0.3.0-dev-1_linux_arm64.tar.gz"
      sha256 "5d08e6ea829c6a18d22d656d2c03d67bc5b4c9ce88bd02f2f766dc44517c9e00"

      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.3.0-dev-1/training-cli_v0.3.0-dev-1_linux_amd64.tar.gz"
      sha256 "587b15826b1afbdaca1dc6ef2a10880f08d9e1a9f09a97eccdc24dc2b52b7ee1"

      def install
        bin.install "training-cli"
      end
    end
  end

  conflicts_with "training-cli"

  def caveats; <<~EOS
    How to use this binary: https://github.com/ondrejsika/training-cli
  EOS
  end

  test do
    system "#{bin}/training-cli version"
  end
end
