# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrainingCliEdge < Formula
  desc "training-cli"
  homepage "https://github.com/ondrejsika/training-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.5.0/training-cli_v0.5.0_darwin_arm64.tar.gz"
      sha256 "c5bf422ed9e25aaec0baa26316fdf768536181bc01e9c11007c44281c452b285"

      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.5.0/training-cli_v0.5.0_darwin_amd64.tar.gz"
      sha256 "a59692b99e46f60083a2786ff36560b6c7526a9e27ac71fffa0a7dc5380ea757"

      def install
        bin.install "training-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.5.0/training-cli_v0.5.0_linux_arm64.tar.gz"
      sha256 "b7109901f7f2067937bdd2f411701051d41c0dbe3588e0e42ed052d1663fc8e0"

      def install
        bin.install "training-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/training-cli/releases/download/v0.5.0/training-cli_v0.5.0_linux_amd64.tar.gz"
      sha256 "0b43157ab99bd10c6ff426fb2aaae3acf8dc647b478c2b652145aa4f21819118"

      def install
        bin.install "training-cli"
      end
    end
  end

  conflicts_with "training-cli"

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/training-cli
    EOS
  end

  test do
    system "#{bin}/training-cli version"
  end
end
